kernel: pf_ring: fix old-style-declaration compilation warning
New kernel linux from 6.12 enabled new compilation Warning and this
cause errors if -Werror is enabled.

There is currently one line that triggers the following warning:

pf_ring.c:284:1: error: 'static' is not at beginning of declaration [-Werror=old-style-declaration]
  284 | const static ip_addr ip_zero = { IN6ADDR_ANY_INIT };
      | ^~~~~

Implement the trivial fix to mute the warning.

Signed-off-by: Christian Marangi <ansuelsmth@gmail.com>